kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brownout-cr
rules:
  - apiGroups: ["", "metrics.k8s.io"] # "" indicates the core API group
    resources: ["nodes", "pods", "deployments"]
    verbs: ["get", "list", "update", "delete", "patch", "create" ]
