kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brownout-crb
subjects:
  - kind: ServiceAccount
    name: brownout-sa
    namespace: wso2 #Namespace set to wso2 for testing due to WSO2 IS deployment
roleRef:
  kind: ClusterRole
  name: brownout-cr
  apiGroup: rbac.authorization.k8s.io
